# Generated by Django 5.0.1 on 2024-02-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NationaliD', models.TextField(blank=True, max_length=50, null=True)),
                ('InformationSource', models.TextField(blank=True, max_length=100, null=True)),
                ('FullName', models.TextField(blank=True, max_length=50, null=True)),
                ('FirstName', models.TextField(max_length=50)),
                ('SecondName', models.TextField(blank=True, max_length=50, null=True)),
                ('ThirdName', models.TextField(blank=True, max_length=50, null=True)),
                ('FourthName', models.TextField(blank=True, max_length=50, null=True)),
                ('FamilyName', models.TextField(max_length=50)),
                ('EnglishName', models.TextField(blank=True, max_length=50, null=True)),
                ('EnglishFirstName', models.TextField(max_length=50)),
                ('EnglishSecondName', models.TextField(blank=True, max_length=50, null=True)),
                ('EnglishThirdName', models.TextField(blank=True, max_length=50, null=True)),
                ('EnglishFourthName', models.TextField(blank=True, max_length=50, null=True)),
                ('EnglishFamilyName', models.TextField(max_length=50)),
                ('BirthName', models.TextField(blank=True, max_length=50, null=True)),
                ('BirthData', models.DateField()),
                ('age', models.IntegerField()),
                ('BirthCity', models.TextField(blank=True, max_length=50, null=True)),
                ('EnglishBirthCity', models.TextField(blank=True, max_length=50, null=True)),
                ('BirthCountry', models.CharField(choices=[('Egypt', 'Egypt'), ('Japan', 'Japan'), ('Brazil', 'Brazil')], max_length=50)),
                ('gander', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50)),
                ('maritalStatus', models.CharField(blank=True, choices=[('single', 'single'), ('married', 'married')], max_length=50, null=True)),
                ('Reigon', models.CharField(choices=[('Reigon x', 'Reigon x'), ('Reigon z', 'Reigon z'), ('Reigon y', 'Reigon y')], max_length=50)),
                ('ReigonSector', models.CharField(blank=True, choices=[('Region Sector x', 'Region Sector x'), ('Region Sector z', 'Region Sector z'), ('Region Sector y', 'Region Sector y')], max_length=50, null=True)),
                ('Nationalty', models.CharField(choices=[('United Kingdom', 'United Kingdom'), ('Uruguay', 'Uruguay'), ('United States', 'United States')], max_length=50)),
                ('NationaltyCategory', models.CharField(choices=[('United Kingdom', 'United Kingdom'), ('Uruguay', 'Uruguay'), ('United States', 'United States')], max_length=50)),
                ('image', models.ImageField(upload_to='profile/')),
            ],
        ),
    ]
